//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rent_CLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car_Type()
        {
            this.Cars_for_Rent = new HashSet<Cars_for_Rent>();
        }
    
        public string Company_Name { get; set; }
        public string Model { get; set; }
        public decimal Cost_pre_Day { get; set; }
        public decimal Delay_Cost_per_Day { get; set; }
        public int Manufactured_Year { get; set; }
        public bool isGear { get; set; }
        public int Model_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars_for_Rent> Cars_for_Rent { get; set; }
    }
}
