//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rent_CLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_for_Rent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars_for_Rent()
        {
            this.Rentals = new HashSet<Rental>();
        }
    
        public int License { get; set; }
        public int Car_Type_Id { get; set; }
        public int Distance_Usage { get; set; }
        public bool IsUsable { get; set; }
        public bool IsAvalible { get; set; }
        public int Branch_Id { get; set; }
        public byte[] CarImage { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Car_Type Car_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
