//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rent_CLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Car_RentalsEntities4 : DbContext
    {
        public Car_RentalsEntities4()
            : base("name=Car_RentalsEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branchs { get; set; }
        public virtual DbSet<Rental> Rentals { get; set; }
        public virtual DbSet<Car_Type> Car_Types { get; set; }
        public virtual DbSet<Cars_for_Rent> Cars_for_Rents { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
